import type { Metadata } from "next";
import { Poppins, Roboto_Mono } from "next/font/google";
import "keen-slider/keen-slider.min.css";
import "./globals.scss";
import "../styles/icons.scss";
import Overview from "../components/overview/overview";
import BgShadow from "@/components/BgShadow/Bgshadow";
import Footer from "@/components/Footer/Footer";
import Menu from "@/components/Menu/Menu";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "800"],
  variable: "--font-poppins",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-1ycn6IcaQQ40/MKB4Imkb9n6...etc"
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={`${poppins.variable} ${robotoMono.variable}`}>
        <div className="app-root">
          <div className="app-wrapper">
            <Overview />
            <main>
              <BgShadow />
              {children}
              <Footer />
            </main>
            <aside>
              <Menu />
            </aside>
          </div>
        </div>
      </body>
    </html>
  );
}
